apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'rook-ceph-cluster-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: 'https://charts.rook.io/release'
        targetRevision: v1.15.7
        chart: rook-ceph-cluster
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: '{{url}}'
        namespace: rook-ceph
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
