apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-secret-prod
  namespace: argocd
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"  # Optional: edits the secret in place
spec:
  dnsNames:
    - argocd.proficientnowtech.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: argocd-secret-prod
  usages:
    - digital signature
    - key encipherment