# File: deployments/domains/infrastructure/apps/platform/argocd/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: argocd.localdev.me # We'll use this for local testing
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
