apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - config-patch.yaml
  - clusterissuer.yaml
  - certificate.yaml
#  currently disabling
# - serviceaccounts.yaml
# - projects.yaml
