# deployments/domains/infrastructure/platform/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infrastructure apps
  - app-networking.yaml
  - app-security.yaml
  - app-observability.yaml
  - app-storage.yaml