# File: deployments/domains/infrastructure/apps/networking/base/ingress-nginx/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.8.3
    chart: ingress-nginx
    helm:
      values: |
        controller:
          name: nginx-ingress
          containerPort:
            http: 80
            https: 443
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
          hostPort:
            enabled: true
          publishService:
            enabled: true
          config:
            compute-full-forwarded-for: "true"
            use-forwarded-headers: "true"
            proxy-buffer-size: "16k"
            # Additional useful configurations
            keep-alive: 75
            keep-alive-requests: 100
            client-header-buffer-size: "1k"
            client-body-buffer-size: "128k"
            large-client-header-buffers: "48k"
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "10254"
          extraArgs:
            enable-ssl-passthrough: true
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-networking-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
