# File: deployments/domains/infrastructure/apps/networking/base/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: infra-networking-ingress
  labels:
    domain: infrastructure
    component: networking
    type: ingress-controller
