# File: deployments/bootstrap/platform-apps/base/domains/infrastructure/argocd-main.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-configuration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pnow-devsupreme/argo.git
    targetRevision: HEAD
    path: deployments/domains/infrastructure/apps/argocd-config/environments/staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
