# File: deployments/domains/infrastructure/apps/networking/environments/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |
      - op: replace
        path: /spec/source/targetRevision
        value: 4.8.3
    target:
      kind: Application
      name: ingress-nginx
