# rook-ceph-operator.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: v1.12.3
    helm:
      values: |-
        image:
          repository: rook/ceph
          tag: v1.12.3
          pullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        tolerations:
          - effect: NoSchedule
            operator: Exists
        nodeSelector: {}
        # monitoring:
          # enabled: true
          # createPrometheusRules: true
        crds:
          enabled: true
        csi:
          enableRbdDriver: true
          enableCephfsDriver: true
          # Enable OMAP for better volume management
          enableOMAPGenerator: true
          provisionerReplicas: 2
        # Enable device discovery
        discover:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
