apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.rook.io/release'
    targetRevision: v1.15.7
    chart: rook-ceph
    helm:
      values: |-
        # CRD Configuration
        crds:
          enabled: true

        # Image Configuration
        image:
          repository: docker.io/rook/ceph
          pullPolicy: IfNotPresent
          tag: v1.15.7

        # Resource Configuration
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 128Mi

        # Security Configuration
        pspEnable: false
        rbacEnable: true
        securityContext:
          runAsUser: 2016
          runAsGroup: 2016
          fsGroup: 2016
        containerSecurityContext:
          runAsNonRoot: true
          runAsUser: 2016
          runAsGroup: 2016
          capabilities:
            drop: ["ALL"]

        # Node Placement Configuration
        nodeSelector:
          kubernetes.io/hostname: "k8s-master.pnhyd.local"
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        placement:
          all:
            nodeSelector:
              kubernetes.io/hostname: "k8s-master.pnhyd.local"
            tolerations:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
                effect: NoSchedule

        # CSI Configuration
        csi:
          enableCSIHostNetwork: true
          provisionerReplicas: 2
          enableCSIEncryption: true
          logLevel: "0"
          enableVolumeReplication: true

          # CSI Resources
          csiRBDProvisionerResource:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          csiRBDPluginResource:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

          # CSI Topology
          topology:
            enabled: true
            domainLabels:
              - kubernetes.io/hostname
              - topology.kubernetes.io/zone

          # CSI Node Placement
          provisionerTolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          pluginTolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          provisioner:
            nodeSelector:
              kubernetes.io/hostname: "k8s-master.pnhyd.local"
          plugin:
            nodeSelector:
              kubernetes.io/hostname: "k8s-master.pnhyd.local"

        # Discovery Configuration
        enableDiscoveryDaemon: true
        discoveryDaemonInterval: "60m"
        discover:
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - k8s-master.pnhyd.local

        # Logging Configuration
        logLevel: INFO

        # Priority Configuration
        priorityClassName: system-cluster-critical

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true