apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  generators:
    # Using a list generator to manage multiple clusters or environments
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            environment: production
  template:
    metadata:
      name: 'rook-ceph-operator-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/rook/rook' # Official Rook release repository
        targetRevision: v1.15.7 # Specify the desired version
        chart: rook-ceph
        helm:
          # Reference to our values file in the Git repository
          valueFiles:
            - values.yaml
      destination:
        server: '{{url}}'
        namespace: rook-ceph # As recommended in the documentation
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
