# File: deployments/domains/infrastructure/apps/networking/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: networking-kustomize
resources:
  - ingress-nginx
